import unittest
from Config.config import login_data, images, csv_files_path
from sge_functions.sge_functions import sge_functions
from Config.config import csv_files_path
from Config.config import txt_files_path
from ddt import ddt, file_data
from sge_functions.sge_functions2 import sge_functions2

#@ddt
class SgePoUnittest(unittest.TestCase):

    #@file_data("./Config/TestDataset/dataSet_ddt_po.json")
    def test_PurchaseOrder_Creacion_Nacional_SINDSO(self):


        sge_funct = sge_functions2()
        print("1,Ingresar a SGE con el usuario de perfil almacen con las credenciales <<User>> <Password>>,")
        sge_funct.sge_connection(login_data.linux_username, login_data.ip, login_data.password)
        conectado = sge_funct.validate_sge_connection()
        if conectado:
       
            print("2 Teclear input  Enter")
            sge_funct.press_enter()
            print("3 Teclear input  Enter")
            sge_funct.press_enter()
            print("4 Seleccionar <<Sucursal>> 12")
            sge_funct.send_text()
            print("5 Teclear input  Enter")
            sge_funct.press_enter()
            print("6 Seleccionar <<OPCION MENU>> 2")
            sge_funct.send_text()
            print("7 Teclear input  Enter")
            sge_funct.press_enter()
            print("8 Seleccionar <<OPCION MENU>> 4")
            sge_funct.send_text()
            print("9 Teclear input  Enter")
            sge_funct.press_enter()
            print("10 Seleccionar <<OPCION MENU>> 10")
            sge_funct.send_text()
            print("11 Teclear input  Enter")
            sge_funct.press_enter()
            print("12 Seleccionar <<OPCION MENU>> 1")
            sge_funct.send_text()
            print("13 Situarse en Proveedor y dar click en la combinacion Ctrl + E ctrl+e")
            print("14 Teclear primeras letras del proveedor configurado <<Proveedor>> TENNECO")
            print("15 Teclear input  Enter")
            sge_funct.press_enter()
            print("16 Situarse en Desglosar DSO presionando la tecla tab 4 veces tab")
            print("17 Teclear input  tab")
            print("18 Teclear input  tab")
            print("19 Teclear input  tab")
            print("20 Teclear input  n")
            sge_funct.send_text()
            print("21 Presionar la combinacion de teclas: Ctrl + W ctrl+w")
            print("22 Ingresar en Login el <<UsarioCompras>> sfabian")
            sge_funct.send_text()
            print("23 Teclear input  Enter")
            sge_funct.press_enter()
            print("24 Abrir y copiar contenido de archivo <<Datos_productos_po.xlsx>> read_file")
            print("25 Teclear input para pegar los items a la ventana de Carga Masiva de Ordenes de compra rclick")
            print("26 Presionar la combinacion de teclas: Ctrl + W ctrl+w")
            print("27 Presionar la combinacion de teclas: Ctrl + W ctrl+w")
            print("28 Ingresar en Login de el <<Usuario>> sfabian")
            sge_funct.send_text()
            print("29 Teclear input  Enter")
            sge_funct.press_enter()
            print("30 Presionar la combinacion de teclas: Ctrl + W ctrl+w")
            print("31 Presionar la combinacion de teclas: Ctrl + W ctrl+w")
            print("32 Seleccionar la Orden de compra dando input dobleclickizquierdo")
            print("33 Teclear input  Enter")
            sge_funct.press_enter()
            print("34 Teclear input  2")
            sge_funct.send_text()
            print("35 Situarse en la orden de compra e ingresar el numero de PO. rclick")
            print("36 Teclear input  Enter")
            sge_funct.press_enter()
            print("37 Teclear input  s")
            sge_funct.send_text()
            print("38 Teclear input  Enter")
            sge_funct.press_enter()
            print("39 Presionar la combinacion de teclas: Ctrl + K ctrl+k")
            print("40 Ingresar en Login el <<UsarioCompras>> sfabian")
            sge_funct.send_text()
            print("41 Teclear input  Enter")
            sge_funct.press_enter()
            print("42 Presionar la combinacion de teclas: Ctrl + K ctrl+k")
            print("43 Ingresar en Login el <<UsarioCompras>> sfabian")
            sge_funct.send_text()
            print("44 Teclear input  Enter")
            sge_funct.press_enter()
            print("45 Cerrar sesion  CerrarSesion")
            print("46 Abrir nueva terminal para ejecucion de Job AbrirNuevaTerminal")
            print("47 Ingresar al SFTP con las <<Credenciales>>  User: itmx12")
            print("48 Dentro del SFTP dirigirse a la <<RUTA>> /cacheJAVA/recibidos_uat/")
            print("49 Ingresar archivo de factura VALIDA INCOMPLETA INV en la carpeta de la ruta. subirfactura")
            print("50 Ejecutar JOB FACTURAS utilizando un usuario con los permisos necesarios y capaz de utilizar linea de comandos bash procesa_EDI.sh REC_INVOICE_TXT")
            print("51 Cerrar terminal Ejecucion jobs CerrarVentanaJobs")
            print("52 Abrir nueva terminal de SGE AbrirNuevoSge")
            print("53 Presionar la combinacion de teclas: Ctrl + a ctrl+a")
            print("54 Teclear input  s")
            sge_funct.send_text()
            print("55 Teclear input  Enter")
            sge_funct.press_enter()
            print("56 Teclear input  2")
            sge_funct.send_text()
            print("57 Situarse en la orden de compra e ingresar el numero de PO. rclick")
            print("58 Teclear input  Enter")
            sge_funct.press_enter()
            print("59 Teclear input  s")
            sge_funct.send_text()
            print("60 Teclear input  Enter")
            sge_funct.press_enter()
            print("61 Situarse en la secuencia 001 con el input flechaabajo")
            print("62 Presionar la combinacion de teclas: Ctrl + k ctrl+k")
            print("63 Ingresar en Login del <<UsuarioAlmacen>>  <<UsuarioAlmacen>>      <<PassAlmacen>>")
            print("64 Teclear input  Enter")
            sge_funct.press_enter()
            print("65 Presionar la combinacion de teclas: Ctrl + a ctrl+a")
            print("66 Presionar la combinacion de teclas: Ctrl + k ctrl+k")
            print("67 Ingresar en Login del <<UsuarioAlmacen>>  <<UsuarioAlmacen>>      <<PassAlmacen>>")
            print("68 Teclear input  Enter")
            sge_funct.press_enter()
            print("69 Cerrar terminal SGE CerrarSge")
            print("70 Abrir terminal con usuario ALMACEN ")
            print("71 Seleccionar <<Sucursal>> 12")
            sge_funct.send_text()
            print("72 Teclear input  Enter")
            sge_funct.press_enter()
            print("73 Seleccionar <<OPCION MENU>> 2")
            sge_funct.send_text()
            print("74 Teclear input  Enter")
            sge_funct.press_enter()
            print("75 Seleccionar <<OPCION MENU>> 4")
            sge_funct.send_text()
            print("76 Teclear input  Enter")
            sge_funct.press_enter()
            print("77 Seleccionar <<OPCION MENU>> 10")
            sge_funct.send_text()
            print("78 Teclear input  Enter")
            sge_funct.press_enter()
            print("79 Seleccionar <<OPCION MENU>> 7")
            print("80 Ingresar el proveedor configurado TENNECO")
            print("81 Teclear input  Enter")
            sge_funct.press_enter()
            print("82 Buscar la factura configurada y pegarla rclick")
            print("83 Presionar la combinacion de teclas: Ctrl + f ctrl+f")
            print("84 Ingresar <<usuarioAlmacen>> jmartin")
            sge_funct.send_text()
            print("85 Teclear input  Enter")
            sge_funct.press_enter()
            print("86 Presionar la combinacion de teclas: Ctrl + A ctrl+a")
            print("87 Cerrar terminal SGE CerrarSge")
            print("88 Abrir terminal con usuario ALMACEN ")
            print("89 Seleccionar <<Sucursal>> 12")
            sge_funct.send_text()
            print("90 Teclear input  Enter")
            sge_funct.press_enter()
            print("91 Seleccionar <<OPCION MENU>> 2")
            sge_funct.send_text()
            print("92 Teclear input  Enter")
            sge_funct.press_enter()
            print("93 Seleccionar <<OPCION MENU>> 4")
            sge_funct.send_text()
            print("94 Teclear input  Enter")
            sge_funct.press_enter()
            print("95 Seleccionar <<OPCION MENU>> 2")
            sge_funct.send_text()
            print("96 Teclear input  Enter")
            sge_funct.press_enter()
            print("97 Ingresar input a")
            print("98 Presionar la combinacion de teclas: Ctrl + b ctrl+b")
            print("99 Ingresar <<proveedor>> configurado TENNECO")
            sge_funct.send_text()
            print("100 Teclear input  Enter")
            sge_funct.press_enter()
            print("101 Buscar la factura configurada ")
            print("102 Teclear input  Enter")
            sge_funct.press_enter()
            print("103 Presionar la combinacion de teclas: Ctrl + w ctrl+w")
            print("104 Presionar la combinacion de teclas: Ctrl + w ctrl+w")
            print("105 Teclear input  Enter")
            sge_funct.press_enter()
            print("106 Presionar la combinacion de teclas: Ctrl + a ctrl+a")
            print("107 Teclear input  10")
            sge_funct.send_text()
            print("108 Teclear input  Enter")
            sge_funct.press_enter()
            print("109 Seleccionar <<OPCION MENU>> 2")
            sge_funct.send_text()
            print("110 Teclear input  Enter")
            sge_funct.press_enter()
            print("111 Situarse en la orden de compra e ingresar el numero de PO. ")
            print("112 Teclear input  Enter")
            sge_funct.press_enter()
            print("113 Teclear input  S")
            sge_funct.send_text()
            print("114 Teclear input  Enter")
            sge_funct.press_enter()

            print("Validating Purchase Order creation")
            nombre_status = "confirmada por proveedor"
            img_status_confirmada = images.img_status_confirmada_por_proveedor

            if sge_funct.validar_po_status2(img_status_confirmada, nombre_status):
                print(f"Status {nombre_status} validado correctamente")
                print("Creando archivos: factura valida y factura invalida")
                #en carpetas de tmp
                sge_funct.crear_factura_valida_e_invalida_txt()
            else:
                print("Fallo validacion, estatus Incorrecto")
                assert False, "Fallo validacion, estatus Incorrecto"

        else:
            print(conectado)
            assert False, "Connection Failed!"



    def tearDown(self):
        sge_funct = sge_functions()
        sge_funct.terminate_sge_session()


if __name__ == '__main__':
    unittest.main()
